### ISSUE TITLE
Versioning scheme?

### ISSUE THREAD

**Issue by jaimergp** [conda/conda-classic-solver#4]
This code has been traditionally part of `conda`, so it was released along with the full application. Now, as a plugin, which version scheme should it follow? My guess is that we'll use calver as we do in conda-libmamba-solver, but let's make that decision explicit here.

cc @jezdez

**Comment by jezdez** [comment]
I don't see a reason to apply SemVer here TBH, so let's go with CalVer since that nicely encodes the time when we removed it from conda as well.

@conda/conda-core Any concerns around that?

**Comment by chenghlee** [comment]
I'm all for aligning with the other projects and using CalVer.

**Comment by jaimergp** [comment]
Calver it is!
